import type { OxlintConfig } from 'oxlint';
import { defineConfig } from 'oxlint';

const config: OxlintConfig = defineConfig<OxlintConfig>({
    categories: {
        correctness: 'error',
        nursery: 'off',
        pedantic: 'error',
        perf: 'error',
        restriction: 'off',
        style: 'off',
        suspicious: 'error',
    },
    env: { browser: true, node: true },
    ignorePatterns: [
        '.agents',
        'docs',
        'pnpm-lock.yaml',
        '**/routeTree.gen.ts',
        '**/next-env.d.ts',
    ],
    plugins: [
        'eslint',
        'import',
        'jsdoc',
        'node',
        'oxc',
        'promise',
        'typescript',
        'unicorn',
    ],
    rules: {
        'eslint/arrow-body-style': 'off',
        'eslint/curly': ['error', 'all'],
        'eslint/default-param-last': 'error',
        'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
        'eslint/func-names': 'off',
        'eslint/grouped-accessor-pairs': 'error',
        'eslint/max-classes-per-file': 'off',
        'eslint/max-depth': ['error', 3],
        'eslint/max-lines': 'off',
        'eslint/max-lines-per-function': 'off',
        'eslint/max-nested-callbacks': ['error', 3],
        'eslint/max-params': ['error', 5],
        'eslint/no-alert': 'error',
        'eslint/no-bitwise': ['error', { int32Hint: true }],
        'eslint/no-div-regex': 'error',
        'eslint/no-inline-comments': 'off',
        'eslint/no-new': 'error',
        'eslint/no-plusplus': 'off',
        'eslint/no-restricted-globals': [
            'error',
            'document',
            'history',
            'location',
            'navigator',
        ],
        'eslint/no-unneeded-ternary': 'error',
        'eslint/no-unused-vars': 'error',
        'eslint/no-warning-comments': 'off',
        'eslint/radix': 'error',
        'eslint/require-await': 'error',
        'eslint/sort-keys': [
            'error',
            'asc',
            {
                allowLineSeparatedGroups: true,
                caseSensitive: false,
                natural: true,
            },
        ],
        'eslint/vars-on-top': 'error',

        'import/export': 'error',
        'import/exports-last': 'error',
        'import/group-exports': 'error',
        'import/max-dependencies': 'off',
        'import/namespace': 'off',
        'import/no-anonymous-default-export': 'error',
        'import/no-cycle': 'error',
        'import/no-mutable-exports': 'error',
        'import/no-named-as-default': 'off',
        'import/no-unassigned-import': 'off',
        'import/prefer-default-export': 'off',

        'jsdoc/require-param': 'off',
        'jsdoc/require-returns': 'off',

        'oxc/no-accumulating-spread': 'off',
        'oxc/no-barrel-file': 'error',
        'oxc/no-map-spread': 'off',

        'react/button-has-type': ['error', { reset: true }],
        'react/capitalized-calls': 'error',
        'react/error-boundaries': 'error',
        'react/exhaustive-deps': [
            'error',
            {
                additionalHooks:
                    '(useCustomLegacyEffect|useCustomEffect|useCustomCallback)',
            },
        ],
        'react/exhaustive-effect-dependencies': 'error',
        'react/globals': 'error',
        'react/hooks': 'error',
        'react/immutability': 'error',
        'react/incompatible-library': 'error',
        'react/invariant': 'error',
        'react/jsx-filename-extension': ['error', { extensions: ['.tsx'] }],
        'react/jsx-fragments': 'error',
        'react/jsx-key': ['error', { checkFragmentShorthand: true }],
        'react/jsx-props-no-spreading': 'off',
        'react/memo-dependencies': 'error',
        'react/no-array-index-key': 'error',
        'react/no-clone-element': 'off',
        'react/no-danger': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-deriving-state-in-effects': 'error',
        'react/no-react-children': 'off',
        'react/preserve-manual-memoization': 'error',
        'react/purity': 'error',
        'react/react-in-jsx-scope': 'off',
        'react/refs': 'error',
        'react/rule-suppression': 'error',
        'react/rules-of-hooks': 'error',
        'react/set-state-in-effect': 'error',
        'react/set-state-in-render': 'error',
        'react/static-components': 'error',
        'react/style-prop-object': 'error',
        'react/syntax': 'error',
        'react/todo': 'error',
        'react/unsupported-syntax': 'error',
        'react/use-memo': 'error',
        'react/void-use-memo': 'error',

        'react-perf/jsx-no-jsx-as-prop': 'off',
        'react-perf/jsx-no-new-array-as-prop': 'off',
        'react-perf/jsx-no-new-function-as-prop': 'off',
        'react-perf/jsx-no-new-object-as-prop': 'off',

        'typescript/consistent-type-definitions': ['error', 'interface'],
        'typescript/consistent-type-exports': 'error',
        'typescript/consistent-type-imports': [
            'error',
            {
                disallowTypeAnnotations: true,
                fixStyle: 'separate-type-imports',
                prefer: 'type-imports',
            },
        ],
        'typescript/no-non-null-assertion': 'error',
        'typescript/no-useless-empty-export': 'error',
        'typescript/no-var-requires': 'error',
        'typescript/require-await': 'error',

        'unicorn/no-abusive-eslint-disable': 'error',
        'unicorn/no-empty-file': 'off',
        'unicorn/no-length-as-slice-end': 'error',
        'unicorn/no-process-exit': 'error',
        'unicorn/prefer-dom-node-append': 'off',
        'unicorn/prefer-dom-node-remove': 'off',
        'unicorn/prefer-modern-math-apis': 'error',
        'unicorn/prefer-node-protocol': 'error',
        'unicorn/prefer-set-has': 'error',
    },
});

export default config;
