// oxlint-disable sort-keys
import type { OxlintConfig } from 'oxlint';
import { defineConfig } from 'oxlint';

const config: OxlintConfig = defineConfig({
    plugins: [
        'eslint',
        'import',
        'typescript',
        'unicorn',
        'oxc',
        'promise',
        'node',
        'jsdoc',
    ],
    env: {
        browser: true,
        node: true,
    },
    categories: {
        correctness: 'error',
        suspicious: 'error',
        pedantic: 'error',
        perf: 'error',
        style: 'off',
        restriction: 'off',
        nursery: 'off',
    },
    ignorePatterns: ['.agents', 'build', 'dist', 'docs'],
    settings: {},
    rules: {
        'unicorn/no-empty-file': 'off',
        'unicorn/prefer-set-has': 'error',
        'promise/catch-or-return': 'error',
        'unicorn/prefer-node-protocol': 'error',
        'typescript/no-non-null-assertion': 'error',
        'oxc/no-barrel-file': 'error',
        'unicorn/no-abusive-eslint-disable': 'error',
        'eslint/no-new': 'error',
        'eslint/radix': 'error',
        'import/no-extraneous-dependencies': 'error',
        'import/no-anonymous-default-export': 'error',
        'import/prefer-default-export': 'off',
        'import/namespace': 'off',
        'import/no-named-as-default': 'off',
        'import/no-cycle': ['error'],
        'react/style-prop-object': 'error',
        'unicorn/prefer-modern-math-apis': 'error',
        'unicorn/no-length-as-slice-end': 'error',
        'import/no-unassigned-import': 'off',
        'eslint/default-param-last': 'error',
        'eslint/no-alert': 'error',
        'eslint/grouped-accessor-pairs': 'error',
        'eslint/no-restricted-globals': [
            'error',
            'document',
            'history',
            'location',
            'navigator',
        ],
        'eslint/curly': ['error', 'all'],
        'eslint/no-div-regex': 'error',
        'eslint/vars-on-top': 'error',
        'eslint/func-names': 'off',
        'eslint/max-depth': ['error', 3],
        'eslint/max-nested-callbacks': ['error', 3],
        'eslint/max-params': ['error', 5],
        'eslint/no-bitwise': ['error', { int32Hint: true }],
        'eslint/no-plusplus': 'off',
        'eslint/arrow-body-style': 'off',
        'eslint/eqeqeq': ['error', 'always', { null: 'ignore' }],
        'eslint/sort-keys': [
            'error',
            'asc',
            {
                allowLineSeparatedGroups: true,
                caseSensitive: false,
                natural: true,
            },
        ],
        'typescript/no-var-requires': 'error',
        'eslint/no-unused-vars': 'error',
        'typescript/consistent-type-definitions': ['error', 'interface'],
        'typescript/consistent-type-imports': [
            'error',
            {
                prefer: 'type-imports',
                fixStyle: 'separate-type-imports',
                disallowTypeAnnotations: true,
            },
        ],
        'eslint/no-unneeded-ternary': 'error',
        'eslint/require-await': 'error',
        'eslint/max-lines-per-function': 'off',
        'eslint/max-lines': 'off',
        'eslint/no-inline-comments': 'off',
        'eslint/max-classes-per-file': 'off',
        'import/max-dependencies': 'off',
        'jsdoc/require-returns': 'off',
        'jsdoc/require-param': 'off',
        'unicorn/prefer-dom-node-remove': 'off',
        'unicorn/prefer-dom-node-append': 'off',
    },
});

export default config;
