name: CI

on:
    push:
        branches: [master]
    pull_request:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: tomek-f/action-pnpm@680dabcd30d0e7f9a8a7907918c54a044204a9af # v2.0.0
            - run: pnpm build

    lint:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: tomek-f/action-pnpm@680dabcd30d0e7f9a8a7907918c54a044204a9af # v2.0.0
            - run: pnpm lint

    types:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: tomek-f/action-pnpm@680dabcd30d0e7f9a8a7907918c54a044204a9af # v2.0.0
            - run: pnpm check-types

    format-check:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: tomek-f/action-pnpm@680dabcd30d0e7f9a8a7907918c54a044204a9af # v2.0.0
            - run: pnpm format-check

    test:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: tomek-f/action-pnpm@680dabcd30d0e7f9a8a7907918c54a044204a9af # v2.0.0
            - run: pnpm test-ci
            - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: test-reports
                  path: ./test-reports/junit.xml

    zizmor:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
              with:
                  advanced-security: false
